exports.data = [
  {
    DC_DATE: new Date("2025-05-28"),
    UNIT_CODE: "U1",
    CHEMICAL_CODE: "CH001",
    UNIT_NAME: "Unit A",
    CHEMICAL_NAME: "Sulphuric Acid",
    SAP_MAT_CODE: 100101,
    UOM: "Litre",
    STOCK_IN_SAP: 500,
    AVG_DAILY_CONSUMPTION: 40,
    OPENING_BALANCE: 200,
    RECIVE_QTY: 50,
    CONSUMPTION_QTY: 30,
    CLOSING_BALANCE: 220,
    SAP_BALANCE: 215,
    REMARKS: "Normal usage",
    USER_ID: 101,
    DATA_INSERT_DATE: new Date(),
    UPDATE_STATUS: "Synced",
    UPDATE_DATE: new Date(),
    STATUS: "Active"
  },
  {
    DC_DATE: new Date("2025-05-28"),
    UNIT_CODE: "U2",
    CHEMICAL_CODE: "CH002",
    UNIT_NAME: "Unit B",
    CHEMICAL_NAME: "Nitric Acid",
    SAP_MAT_CODE: 100102,
    UOM: "Litre",
    STOCK_IN_SAP: 300,
    AVG_DAILY_CONSUMPTION: 20,
    OPENING_BALANCE: 100,
    RECIVE_QTY: 40,
    CONSUMPTION_QTY: 20,
    CLOSING_BALANCE: 120,
    SAP_BALANCE: 125,
    REMARKS: "Low consumption",
    USER_ID: 102,
    DATA_INSERT_DATE: new Date(),
    UPDATE_STATUS: "Pending",
    UPDATE_DATE: new Date(),
    STATUS: "Active"
  },
  {
    DC_DATE: new Date("2025-05-28"),
    UNIT_CODE: "U3",
    CHEMICAL_CODE: "CH003",
    UNIT_NAME: "Unit C",
    CHEMICAL_NAME: "Hydrochloric Acid",
    SAP_MAT_CODE: 100103,
    UOM: "Litre",
    STOCK_IN_SAP: 450,
    AVG_DAILY_CONSUMPTION: 33,
    OPENING_BALANCE: 300,
    RECIVE_QTY: 30,
    CONSUMPTION_QTY: 60,
    CLOSING_BALANCE: 270,
    SAP_BALANCE: 265,
    REMARKS: "High usage today",
    USER_ID: 103,
    DATA_INSERT_DATE: new Date(),
    UPDATE_STATUS: "Synced",
    UPDATE_DATE: new Date(),
    STATUS: "Active"
  }
];

